#!/bin/bash
REPO="verycosmic/distributed-video-conference"
echo ""
echo "🎥 VIDEO CONFERENCE DEPLOYMENT"
echo "=============================="
echo ""
echo "📋 Repository: $REPO"
echo ""
echo "🌐 Your conference will be at:"
echo "   https://verycosmic.github.io/distributed-video-conference/"
echo ""
echo "📝 Next steps:"
echo "   1. Create Cloudflare workers.dev subdomain (one-time)"
echo "   2. Deploy workers: wrangler deploy"
echo "   3. Add GitHub Secrets (VITE_WS_URL, VITE_TURN_CONFIG_URL)"
echo "   4. Enable GitHub Pages (Source: GitHub Actions)"
echo "   5. Push to GitHub: git push origin main"
echo ""
echo "📖 Full instructions: FINAL_DEPLOYMENT.md"
echo ""
